name: alnabali_driver
description: Alnabali Driver App

publish_to: "none" # Remove this line if you wish to publish to pub.dev

# version and build number for your application.
version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
#  cupertino_icons: ^1.0.2
  rxdart: ^0.27.5
  intl: ^0.17.0
  go_router: ^5.1.1
  url_strategy: ^0.2.0
  dio: ^4.0.6
  freezed_annotation: ^2.2.0
  flutter_screenutil: ^5.6.0
  fluttertoast: ^8.1.1
  flutter_dash: ^1.0.0
  grouped_list: ^5.1.2
  google_maps_flutter: ^2.2.3
  flutter_polyline_points: ^1.0.0
  location: ^4.4.0
  flutter_localizations: 
    sdk: flutter
  localization: ^2.1.0
  firebase_core: ^2.3.0
  firebase_messaging: ^14.1.2
  overlay_support: ^2.1.0
  firebase_analytics: ^10.0.6
  cloud_firestore: ^4.1.0
  flutter_local_notifications: ^12.0.4
  cupertino_icons: ^1.0.5
  flutter_riverpod: 2.0.0-dev.9 #^2.1.1
  shared_preferences: ^2.0.17
  package_info_plus: ^3.1.0
  loading_indicator: ^3.1.0
  url_launcher: ^6.0.12
  image_picker:


  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.3.2
  freezed: ^2.2.0
  #flutter_native_splash: ^2.2.14

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/
    - assets/images/
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.otf
        - asset: assets/fonts/Montserrat-Medium.otf
          weight: 500
        - asset: assets/fonts/Montserrat-SemiBold.otf
          weight: 600
        - asset: assets/fonts/Montserrat-Bold.otf
          weight: 700
        - asset: assets/fonts/Montserrat-ExtraBold.otf
          weight: 800
    - family: AppIcons
      fonts:
        - asset: assets/fonts/AppIcons.ttf
